export const Component = {
  Application: Symbol.for('Application'),
  LoggerInterface: Symbol.for('LoggerInterface'),
  ConfigInterface: Symbol.for('ConfigInterface'),
  DatabaseInterface: Symbol.for('DatabaseInterface'),
  HostServiceInterface: Symbol.for('HostServiceInterface'),
  HostModel: Symbol.for('HostModel'),
  OfferServiceInterface: Symbol.for('OfferServiceInterface'),
  OfferModel: Symbol.for('OfferModel'),
  CommentModel: Symbol.for('CommentModel'),
  CommentServiceInterface: Symbol.for('CommentServiceInterface'),
  HostController: Symbol.for('HostController'),
  OfferController: Symbol.for('OfferController'),
  ExceptionFilterInterface: Symbol.for('ExceptionFilterInterface'),
} as const;
